import type { ChatScript } from "./chat-scripts";

/**
 * Demo mode scripts — 15 contacts with realistic negotiations.
 * All deals are profitable:
 *   - Buys at 1-2% below London Fix
 *   - Sells at 0.5-1.5% above London Fix
 *
 * Mix: 8 buys (UAE), 5 sells (HK), 2 walk-aways (no lock)
 * Staggered: short scripts (3-4 msgs) and long scripts (8-12 msgs)
 */
export const DEMO_SCRIPTS: ChatScript[] = [
  // ─── SELLS (HK buyers) — we sell at premium ───
  {
    contact_name: "Mr. Chang",
    contact_location: "hong_kong",
    metal: "gold",
    purity: "24K",
    quantity_grams: 10000,
    price_per_oz: 2358.5000,
    locks: true,
    buyer_type: "individual",
    payment_currency: "HKD",
    messages: [
      { direction: "incoming", text: "Good morning. I need 10 kg of 24K gold. What's your best price today?" },
      { direction: "outgoing", text: "Good morning Mr. Chang. For 10 kg 24K, I can do $2,362.00/oz." },
      { direction: "incoming", text: "That's a bit high. I'm seeing $2,355 in the market." },
      { direction: "outgoing", text: "Market is $2,341 on the fix. My spread is very tight for 10 kg." },
      { direction: "incoming", text: "Can you come down to $2,356?" },
      { direction: "outgoing", text: "For you Mr. Chang, $2,359 — best I can do on 10 kg." },
      { direction: "incoming", text: "Meet me at $2,358.50 and we have a deal." },
      { direction: "outgoing", text: "$2,358.50 for 10 kg 24K gold. Confirmed." },
      { direction: "incoming", text: "10 Kg 24K Gold at USD 2358.5000 sell — lock" },
      { direction: "outgoing", text: "Locked. Will arrange delivery to HK." },
    ],
  },
  {
    contact_name: "HSBC Hong Kong",
    contact_location: "hong_kong",
    metal: "gold",
    purity: "24K",
    quantity_grams: 25000,
    price_per_oz: 2355.0000,
    locks: true,
    buyer_type: "bank",
    payment_currency: "USD",
    messages: [
      { direction: "incoming", text: "We need 25 kg 24K gold bars for our vault. Standard LBMA good delivery." },
      { direction: "outgoing", text: "25 kg available. $2,357/oz, delivery within 48 hours." },
      { direction: "incoming", text: "$2,354 is our limit. Bank policy." },
      { direction: "outgoing", text: "For HSBC, $2,355. 25 kg is a significant order." },
      { direction: "incoming", text: "Agreed. 25 Kg 24K Gold at USD 2355.0000 sell — lock" },
      { direction: "outgoing", text: "Locked. Wire transfer on delivery. Thank you." },
    ],
  },
  {
    contact_name: "Asia Precious Ltd",
    contact_location: "hong_kong",
    metal: "silver",
    purity: "999",
    quantity_grams: 100000,
    price_per_oz: 30.6200,
    locks: true,
    buyer_type: "individual",
    payment_currency: "HKD",
    messages: [
      { direction: "incoming", text: "We need 100 kg of 999 silver. Large order. Best price?" },
      { direction: "outgoing", text: "100 kg silver 999. $30.75/oz for this volume." },
      { direction: "incoming", text: "Too high. $30.50 is market." },
      { direction: "outgoing", text: "For 100 kg, I can do $30.65." },
      { direction: "incoming", text: "$30.60 and we close now." },
      { direction: "outgoing", text: "$30.62 — splitting the difference. Final." },
      { direction: "incoming", text: "Fine. 100 Kg 999 Silver at USD 30.6200 sell — lock" },
      { direction: "outgoing", text: "Locked. Preparing shipment." },
    ],
  },
  {
    contact_name: "Binance HK",
    contact_location: "hong_kong",
    metal: "platinum",
    purity: "999",
    quantity_grams: 5000,
    price_per_oz: 990.5000,
    locks: true,
    buyer_type: "crypto_exchange",
    payment_currency: "USDT",
    messages: [
      { direction: "incoming", text: "5 kg platinum 999 for our reserves. Price?" },
      { direction: "outgoing", text: "$992/oz for 5 kg platinum." },
      { direction: "incoming", text: "$989? We pay in USDT, instant." },
      { direction: "outgoing", text: "USDT is fine. $990.50 for instant payment." },
      { direction: "incoming", text: "Deal. 5 Kg 999 Platinum at USD 990.5000 sell — lock" },
      { direction: "outgoing", text: "Locked. Send USDT to our wallet." },
    ],
  },
  {
    contact_name: "Wong & Partners",
    contact_location: "hong_kong",
    metal: "palladium",
    purity: "999",
    quantity_grams: 3000,
    price_per_oz: 1032.0000,
    locks: true,
    buyer_type: "individual",
    payment_currency: "HKD",
    messages: [
      { direction: "incoming", text: "3 kg palladium 999 available? Industrial client needs it urgently." },
      { direction: "outgoing", text: "Available. $1,035/oz for urgent delivery." },
      { direction: "incoming", text: "$1,030. They need it today." },
      { direction: "outgoing", text: "$1,032 — urgent premium is fair." },
      { direction: "incoming", text: "OK. 3 Kg 999 Palladium at USD 1032.0000 sell — lock" },
      { direction: "outgoing", text: "Locked. Arranging same-day delivery." },
    ],
  },
  // ─── BUYS (UAE sellers) — we buy at discount ───
  {
    contact_name: "Karim & Co.",
    contact_location: "uae",
    metal: "gold",
    purity: "18K",
    quantity_grams: 3000,
    price_per_oz: 2310.0000,
    locks: true,
    delay_seconds: 20,
    messages: [
      { direction: "incoming", text: "Salaam. We have 3 kg of 18K gold scrap. Good quality." },
      { direction: "outgoing", text: "Wa alaikum assalam. What price?" },
      { direction: "incoming", text: "$2,320/oz for the lot." },
      { direction: "outgoing", text: "18K needs refining. Best I can do is $2,305." },
      { direction: "incoming", text: "$2,315. It's very clean scrap." },
      { direction: "outgoing", text: "$2,310 — final. Refining costs are on us." },
      { direction: "incoming", text: "Agreed. 3 Kg 18K Gold at USD 2310.0000 buy — lock" },
      { direction: "outgoing", text: "Locked. Payment in AED today." },
    ],
  },
  {
    contact_name: "Shah Brothers",
    contact_location: "uae",
    metal: "gold",
    purity: "24K",
    quantity_grams: 2000,
    price_per_oz: 2325.0000,
    locks: true,
    delay_seconds: 35,
    messages: [
      { direction: "incoming", text: "2 kg 24K gold available. Pure LBMA bars." },
      { direction: "outgoing", text: "Price?" },
      { direction: "incoming", text: "$2,330/oz." },
      { direction: "outgoing", text: "$2,325 and I take the lot today." },
      { direction: "incoming", text: "Done. 2 Kg 24K Gold at USD 2325.0000 buy — lock" },
      { direction: "outgoing", text: "Locked. Sending AED now." },
    ],
  },
  {
    contact_name: "Patel Exports",
    contact_location: "uae",
    metal: "silver",
    purity: "999",
    quantity_grams: 5000,
    price_per_oz: 29.5500,
    locks: true,
    delay_seconds: 50,
    messages: [
      { direction: "incoming", text: "5 kg silver 999. Need to clear stock." },
      { direction: "outgoing", text: "I can take it at $29.40/oz." },
      { direction: "incoming", text: "$29.65. Below that I can't go." },
      { direction: "outgoing", text: "$29.55 — quick payment in AED." },
      { direction: "incoming", text: "OK. 5 Kg 999 Silver at USD 29.5500 buy — lock" },
      { direction: "outgoing", text: "Locked. AED transfer in 1 hour." },
    ],
  },
  {
    contact_name: "Dubai Gold Souk Traders",
    contact_location: "uae",
    metal: "gold",
    purity: "22K",
    quantity_grams: 1000,
    price_per_oz: 2315.0000,
    locks: true,
    delay_seconds: 70,
    messages: [
      { direction: "incoming", text: "1 kg 22K gold. Souk special. Clean." },
      { direction: "outgoing", text: "$2,310/oz?" },
      { direction: "incoming", text: "$2,318. It's 22K, almost pure." },
      { direction: "outgoing", text: "22K is 91.7% — needs light refining. $2,315." },
      { direction: "incoming", text: "Fine. 1 Kg 22K Gold at USD 2315.0000 buy — lock" },
      { direction: "outgoing", text: "Locked. Payment ready." },
    ],
  },
  {
    contact_name: "Al Rashid Metals",
    contact_location: "uae",
    metal: "platinum",
    purity: "999",
    quantity_grams: 1000,
    price_per_oz: 968.0000,
    locks: true,
    delay_seconds: 80,
    messages: [
      { direction: "incoming", text: "1 kg platinum 999 from recycling. Available now." },
      { direction: "outgoing", text: "$965/oz for recycled platinum." },
      { direction: "incoming", text: "$970. It's certified 999." },
      { direction: "outgoing", text: "$968 and done." },
      { direction: "incoming", text: "1 Kg 999 Platinum at USD 968.0000 buy — lock" },
      { direction: "outgoing", text: "Locked." },
    ],
  },
  {
    contact_name: "Muscat Gold LLC",
    contact_location: "uae",
    metal: "palladium",
    purity: "999",
    quantity_grams: 500,
    price_per_oz: 1008.0000,
    locks: true,
    delay_seconds: 90,
    messages: [
      { direction: "incoming", text: "500 gm palladium. Urgent sale." },
      { direction: "outgoing", text: "$1,005/oz for urgent." },
      { direction: "incoming", text: "$1,010. It's below market." },
      { direction: "outgoing", text: "$1,008 — quick deal." },
      { direction: "incoming", text: "500 Gm 999 Palladium at USD 1008.0000 buy — lock" },
      { direction: "outgoing", text: "Locked. AED on the way." },
    ],
  },
  {
    contact_name: "Emirates Refinery",
    contact_location: "uae",
    metal: "gold",
    purity: "20K",
    quantity_grams: 2000,
    price_per_oz: 2305.0000,
    locks: true,
    delay_seconds: 120,
    messages: [
      { direction: "incoming", text: "2 kg of 20K gold. Factory surplus." },
      { direction: "outgoing", text: "$2,300/oz for 20K?" },
      { direction: "incoming", text: "$2,308. 20K is 83% pure." },
      { direction: "outgoing", text: "$2,305. Refining costs are significant." },
      { direction: "incoming", text: "Agreed. 2 Kg 20K Gold at USD 2305.0000 buy — lock" },
      { direction: "outgoing", text: "Locked. Sending to refinery today." },
    ],
  },
  // ─── WALK-AWAYS (no lock — realistic) ───
  {
    contact_name: "Li Wei Trading",
    contact_location: "hong_kong",
    metal: "gold",
    purity: "24K",
    quantity_grams: 5000,
    price_per_oz: 0,
    locks: false,
    delay_seconds: 60,
    messages: [
      { direction: "incoming", text: "Price check for 5 kg 24K gold." },
      { direction: "outgoing", text: "$2,360/oz for 5 kg." },
      { direction: "incoming", text: "Too expensive. Waiting for PM fix." },
      { direction: "outgoing", text: "PM fix might go higher. $2,356?" },
      { direction: "incoming", text: "No thanks. I'll check back tomorrow." },
      { direction: "outgoing", text: "OK, let me know." },
    ],
  },
  {
    contact_name: "Kuwait Metals",
    contact_location: "uae",
    metal: "silver",
    purity: "999",
    quantity_grams: 20000,
    price_per_oz: 0,
    locks: false,
    delay_seconds: 150,
    messages: [
      { direction: "incoming", text: "20 kg silver 999. What can you offer?" },
      { direction: "outgoing", text: "$29.35/oz for 20 kg." },
      { direction: "incoming", text: "We got a better offer. $29.50 from someone else." },
      { direction: "outgoing", text: "I can't match that. Good luck." },
      { direction: "incoming", text: "Thanks. Maybe next time." },
    ],
  },
  // ─── WAVE 2: More contacts (stagger the action) ───
  {
    contact_name: "Standard Chartered HK",
    contact_location: "hong_kong",
    metal: "gold",
    purity: "24K",
    quantity_grams: 20000,
    price_per_oz: 2356.0000,
    locks: true,
    buyer_type: "bank",
    payment_currency: "USD",
    messages: [
      { direction: "incoming", text: "Good afternoon. We require 20 kg 24K gold LBMA bars for our custody vault." },
      { direction: "outgoing", text: "20 kg available. $2,360/oz with 48hr delivery." },
      { direction: "incoming", text: "Our compliance approved $2,354 max." },
      { direction: "outgoing", text: "$2,356 for 20 kg. Bank-grade delivery, fully insured." },
      { direction: "incoming", text: "Approved. 20 Kg 24K Gold at USD 2356.0000 sell — lock" },
      { direction: "outgoing", text: "Locked. Invoice follows." },
    ],
  },
  {
    contact_name: "Jumeirah Gold House",
    contact_location: "uae",
    metal: "gold",
    purity: "18K",
    quantity_grams: 3000,
    price_per_oz: 2308.0000,
    locks: true,
    delay_seconds: 130,
    messages: [
      { direction: "incoming", text: "We have 3 kg of 18K jewelry scrap. Melted and ready." },
      { direction: "outgoing", text: "18K scrap — $2,300/oz?" },
      { direction: "incoming", text: "$2,312. It's very clean, minimal impurities." },
      { direction: "outgoing", text: "$2,308 — refining costs are high on 18K." },
      { direction: "incoming", text: "Fine. 3 Kg 18K Gold at USD 2308.0000 buy — lock" },
      { direction: "outgoing", text: "Locked. AED payment today. Sending to refinery." },
    ],
  },
  {
    contact_name: "OKX Exchange",
    contact_location: "hong_kong",
    metal: "silver",
    purity: "999",
    quantity_grams: 75000,
    price_per_oz: 30.5800,
    locks: true,
    buyer_type: "crypto_exchange",
    payment_currency: "USDT",
    messages: [
      { direction: "incoming", text: "75 kg silver 999 for our physical backing reserve. USDT payment." },
      { direction: "outgoing", text: "$30.65/oz for 75 kg. USDT accepted." },
      { direction: "incoming", text: "$30.55?" },
      { direction: "outgoing", text: "$30.58 — instant USDT is worth the slight discount." },
      { direction: "incoming", text: "OK. 75 Kg 999 Silver at USD 30.5800 sell — lock" },
      { direction: "outgoing", text: "Locked. Send USDT to our wallet address." },
    ],
  },
  {
    contact_name: "Bahrain Bullion",
    contact_location: "uae",
    metal: "gold",
    purity: "24K",
    quantity_grams: 2000,
    price_per_oz: 2322.0000,
    locks: true,
    delay_seconds: 140,
    messages: [
      { direction: "incoming", text: "2 kg 24K gold bars. Bahrain certified. Good price." },
      { direction: "outgoing", text: "$2,318/oz for 2 kg 24K." },
      { direction: "incoming", text: "$2,325. Bahrain certification adds value." },
      { direction: "outgoing", text: "$2,322 — fair for certified bars." },
      { direction: "incoming", text: "Deal. 2 Kg 24K Gold at USD 2322.0000 buy — lock" },
      { direction: "outgoing", text: "Locked. AED transfer initiated." },
    ],
  },
  {
    contact_name: "HK Gold Dealers Ltd",
    contact_location: "hong_kong",
    metal: "platinum",
    purity: "999",
    quantity_grams: 8000,
    price_per_oz: 991.5000,
    locks: true,
    buyer_type: "individual",
    payment_currency: "HKD",
    messages: [
      { direction: "incoming", text: "We need 8 kg of 999 platinum for industrial client." },
      { direction: "outgoing", text: "$994/oz for 8 kg." },
      { direction: "incoming", text: "Client budget is $990." },
      { direction: "outgoing", text: "$991.50 — meeting halfway." },
      { direction: "incoming", text: "Agreed. 8 Kg 999 Platinum at USD 991.5000 sell — lock" },
      { direction: "outgoing", text: "Locked. Delivery tomorrow." },
    ],
  },
  {
    contact_name: "Oman Silver Co",
    contact_location: "uae",
    metal: "silver",
    purity: "999",
    quantity_grams: 5000,
    price_per_oz: 29.4500,
    locks: true,
    delay_seconds: 180,
    messages: [
      { direction: "incoming", text: "5 kg silver 999. Surplus from our factory." },
      { direction: "outgoing", text: "$29.30/oz for factory surplus." },
      { direction: "incoming", text: "$29.50. It's certified 999." },
      { direction: "outgoing", text: "$29.45 and I clear the lot today." },
      { direction: "incoming", text: "5 Kg 999 Silver at USD 29.4500 buy — lock" },
      { direction: "outgoing", text: "Locked. AED payment in 2 hours." },
    ],
  },
  {
    contact_name: "Chang Enterprises",
    contact_location: "hong_kong",
    metal: "gold",
    purity: "24K",
    quantity_grams: 6000,
    price_per_oz: 2354.0000,
    locks: true,
    buyer_type: "individual",
    payment_currency: "HKD",
    messages: [
      { direction: "incoming", text: "Hi, this is Mr. Chang's son. We need 6 kg 24K for our retail business." },
      { direction: "outgoing", text: "Hello! For Chang family, $2,358/oz." },
      { direction: "incoming", text: "Father says $2,352." },
      { direction: "outgoing", text: "$2,354 — family rate." },
      { direction: "incoming", text: "Father agreed. 6 Kg 24K Gold at USD 2354.0000 sell — lock" },
      { direction: "outgoing", text: "Locked. Send regards to Mr. Chang senior!" },
    ],
  },
  {
    contact_name: "Abu Dhabi Refinery",
    contact_location: "uae",
    metal: "platinum",
    purity: "999",
    quantity_grams: 1000,
    price_per_oz: 966.0000,
    locks: true,
    delay_seconds: 190,
    messages: [
      { direction: "incoming", text: "1 kg platinum 999. Recycled from catalytic converters." },
      { direction: "outgoing", text: "$963/oz for recycled platinum." },
      { direction: "incoming", text: "$968. It's already refined to 999." },
      { direction: "outgoing", text: "$966 — good deal for both sides." },
      { direction: "incoming", text: "1 Kg 999 Platinum at USD 966.0000 buy — lock" },
      { direction: "outgoing", text: "Locked." },
    ],
  },
  {
    contact_name: "Sharjah Precious",
    contact_location: "uae",
    metal: "gold",
    purity: "22K",
    quantity_grams: 1500,
    price_per_oz: 2312.0000,
    locks: true,
    delay_seconds: 200,
    messages: [
      { direction: "incoming", text: "1.5 kg 22K gold. Wedding season surplus." },
      { direction: "outgoing", text: "$2,308/oz for 22K." },
      { direction: "incoming", text: "$2,315." },
      { direction: "outgoing", text: "$2,312." },
      { direction: "incoming", text: "1.5 Kg 22K Gold at USD 2312.0000 buy — lock" },
      { direction: "outgoing", text: "Locked. Payment in AED." },
    ],
  },
  {
    contact_name: "Singapore Metals",
    contact_location: "hong_kong",
    metal: "palladium",
    purity: "999",
    quantity_grams: 2000,
    price_per_oz: 0,
    locks: false,
    delay_seconds: 270,
    messages: [
      { direction: "incoming", text: "2 kg palladium. Checking prices across suppliers." },
      { direction: "outgoing", text: "$1,033/oz for 2 kg palladium." },
      { direction: "incoming", text: "Let me compare. I have a quote at $1,028." },
      { direction: "outgoing", text: "I can do $1,030." },
      { direction: "incoming", text: "Going with the other supplier. Sorry." },
      { direction: "outgoing", text: "No problem. Next time." },
    ],
  },
];
